const Examples = {
    'Helloworld':[
        'HelloScene.html',
        'HelloNode.html',
        'HelloTexture.html',
        'HelloMaterial.html',
        'HelloMaterialDef.html',
        'HelloEvent.html',
        'HelloGeometry.html',
        'HelloLight.html',
        'HelloShadow.html',
        'HelloTransform.html',
        'HelloSky.html',
        'HelloPicture.html',
    ],
    'Animations':[

    ],
    'Scenes':[
        'Toad.html',
        'Leaves.html',
    ],
    'Skys':[
        'SkyCubeMap.html',
        'SkyCubeMap2.html',
        'SkyEnv.html',
        'SkyEnvHDR.html',
        'EnvCapture.html',
        'GIProbeBake.html',
    ],
    'Lights':[
        "DirectionalLighting.html",
        "PointLighting.html",
        "SpotLighting.html",
        "DynamicPointLighting.html",
        "ManyDynamicPointLighting.html",
        "SinglePassForwardPointLighting.html",
        "SinglePassVsMultiPassLighting.html",
        "LightStepClip.html",
    ],
    'Shadows':[
        'DirectionalLightShadow.html',
        'DynamicDirectionalLightShadow.html',
        'PointLightShadow.html',
        'SpotLightShadow.html',
        'LightMap.html',
        'ParallelSplitShadowMapShadow.html',
        'ParallelSplitShadowMapShadow2.html',
    ],
    'Materials':[
        'Basic.html',
        'MetallicRoughness.html',
        'SpecularGloss.html',
        'PrincipledMaterial.html',
        'PrincipledMaterialMetallicRoughness.html',
        'BasicMaterialVsPrincipledMaterial.html',
        'SpecularGlossVsMetallicRoughness.html',
        'MaterialReplacement.html',
        'EnvironmentMaterial.html',
        'MetallicOrRoughness.html',
    ],
    'Renders':[
        'RenderState.html',
        'RenderToTexture.html',
        'DeferredShading.html',
        'DeferredShadingPBR.html',
        'TileBasedDeferredShading.html',
        'TileBasedDeferredShadingPBR.html',
    ],
    'PostFilters':[
        'BloomFilter.html',
        'GrayFilter.html',
    ],
    'Cameras':[

    ],
    'Geometrys':[
        'BasicShape.html',
    ],
    'Transforms':[

    ],
    'Textures':[

    ],
    'BoundingVolume':[

    ],
    'Maths':[

    ],
    'Optimizations':[
        'FrustumeCulling.html',
        'OctreeCulling.html',
        'LevelOfDetail.html',
    ],
    'Supps':[

    ],
    'Common':[

    ],
};
